### ISSUE TITLE
Rename UIColor change extensions to changed

### ISSUE THREAD

**Issue by fredpi** [Flinesoft/HandyUIKit#4]
To be in-line with Swift naming conventions (as being the case with `.sort()` and `.sorted()` for collections), I'd propose to rename the UIColor `change()` extension to `changed()`. Adding a func `change()` as an addition isn't possible due to the design of `UIColor`.

**Comment by Jeehut** [comment]
I'm closing this here as we already discussed this in person. Here's the conclusion for reference:
I agree that actions like `sort` should be renamed according to the great Swift renaming. But here, we don't have a mere action, it's rather a part of a sentence, see for example this example of the Readme:

```swift
color.change(.luminance, to: 0.8)
```

You can see that the entire line builds a sentence "change luminance to 80%". When using `sort` it's different, it just reads as `sort` which isn't quite english and thus `sorted` is better. Also since we don't have a mutating alternative and Xcode gives warnings when there's a non-discardable return type (which is the case) it shouldn't be a problem here and even be more readable and understandable.

I don't think "changed luminance to 80%" reads well, it would need to be "luminance changed to 80%" which would be a completely different API which I like, too, but is it worth the change? If you feel like it, feel free to send a PR for that.
